apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-data-redis.fullname" . }}
  labels:
    {{- include "spring-data-redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spring-data-redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-data-redis.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
