apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-data-redis
  labels:
    app: spring-data-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-data-redis
  template:
    metadata:
      labels:
        app: spring-data-redis
    spec:
      containers:
        - name: spring-data-redis
          image: myacr002.azurecr.io/spring-data-redis:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:testdb"
            - name: SPRING_DATASOURCE_DRIVERCLASSNAME
              value: "org.h2.Driver"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_REDIS_HOST
              value: "DEV.redis.cache.windows.net"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_REDIS_PASSWORD
              value: "ZRRxdHHEiPzpTTYMNBgU9GFARh8YeBYkeAzCaIPifFs="
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
