apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-data-redis.fullname" . }}
  labels:
    app: {{ include "spring-data-redis.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "spring-data-redis.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "spring-data-redis.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:testdb"
            - name: SPRING_DATASOURCE_DRIVERCLASSNAME
              value: "org.h2.Driver"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_REDIS_HOST
              value: "DEV.redis.cache.windows.net"
            - name: SPRING_REDIS_PORT
              value: "6379"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
